name: marbl-diags
channels:
   - conda-forge
   - default
dependencies:
   - numpy
   - dask
   - xarray
   - matplotlib
   - cartopy
   - pyyaml
   - zarr
   - libnetcdf=4.6.2
   - netcdf4
   - pyyaml
   - esmlab
